version: '3.8'

services:
  myapp:
    build: .
    ports:
      - "8000:8000"  # Map FastAPI port to host
      - "8501:8501"  # Map Streamlit port to host
    volumes:
      - ./logs:/app/logs  # Mount the logs directory
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 &
      streamlit run app.py --server.port 8501 --server.enableCORS false"

